ng add @angular-architects/module-federation --project mfe0 --port 4201
ng add @angular-architects/module-federation --project mfe1 --port 4202
ng add @angular-architects/module-federation --project mfe2 --port 4203
ng add @angular-architects/module-federation --project mfe3 --port 4204
ng add @angular-architects/module-federation --project mfe4 --port 4205
ng add @angular-architects/module-federation --project mfe5 --port 4206
ng add @angular-architects/module-federation --project mfe6 --port 4207
ng add @angular-architects/module-federation --project mfe7 --port 4208
ng add @angular-architects/module-federation --project mfe8 --port 4209
ng add @angular-architects/module-federation --project mfe9 --port 4210
ng add @angular-architects/module-federation --project mfe10 --port 4211
ng add @angular-architects/module-federation --project mfe11 --port 4212
ng add @angular-architects/module-federation --project mfe12 --port 4213
ng add @angular-architects/module-federation --project mfe13 --port 4214
ng add @angular-architects/module-federation --project mfe14 --port 4215
ng add @angular-architects/module-federation --project mfe15 --port 4216
ng add @angular-architects/module-federation --project mfe16 --port 4217
ng add @angular-architects/module-federation --project mfe17 --port 4218
ng add @angular-architects/module-federation --project mfe18 --port 4219
ng add @angular-architects/module-federation --project mfe19 --port 4220
ng add @angular-architects/module-federation --project mfe20 --port 4221
ng add @angular-architects/module-federation --project mfe21 --port 4222
ng add @angular-architects/module-federation --project mfe22 --port 4223
ng add @angular-architects/module-federation --project mfe23 --port 4224
ng add @angular-architects/module-federation --project mfe24 --port 4225
ng add @angular-architects/module-federation --project mfe25 --port 4226
ng add @angular-architects/module-federation --project mfe26 --port 4227
ng add @angular-architects/module-federation --project mfe27 --port 4228
ng add @angular-architects/module-federation --project mfe28 --port 4229
ng add @angular-architects/module-federation --project mfe29 --port 4230
